# Generated by Django 5.0.3 on 2026-06-25 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.FloatField(help_text="Age of the patient (years)")),
                ("sex", models.IntegerField(choices=[(0, "Female"), (1, "Male")])),
                ("smoking", models.BooleanField(default=False)),
                ("diabetes", models.BooleanField(default=False)),
                (
                    "anaemia",
                    models.BooleanField(
                        default=False,
                        help_text="Decrease of red blood cells or hemoglobin",
                    ),
                ),
                ("high_blood_pressure", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creatinine_phosphokinase",
                    models.IntegerField(
                        help_text="Level of the CPK enzyme in the blood (mcg/L)"
                    ),
                ),
                (
                    "ejection_fraction",
                    models.IntegerField(
                        help_text="Percentage of blood leaving the heart at each contraction"
                    ),
                ),
                (
                    "platelets",
                    models.FloatField(
                        help_text="Platelets in the blood (kiloplatelets/mL)"
                    ),
                ),
                (
                    "serum_creatinine",
                    models.FloatField(
                        help_text="Level of serum creatinine in the blood (mg/dL)"
                    ),
                ),
                (
                    "serum_sodium",
                    models.IntegerField(
                        help_text="Level of serum sodium in the blood (mEq/L)"
                    ),
                ),
                (
                    "follow_up_days",
                    models.IntegerField(
                        db_column="time", help_text="Follow-up period (days)"
                    ),
                ),
                (
                    "death_event",
                    models.BooleanField(
                        default=False,
                        help_text="If the patient deceased during the follow-up period",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_records",
                        to="patients.patient",
                    ),
                ),
            ],
        ),
    ]
